`timescale 1ns/1ps
// Generated by Cadence Genus(TM) Synthesis Solution 18.14-s037_1
// Generated on: Nov 18 2025 20:41:25 CST (Nov 19 2025 02:41:25 UTC)

// Verification Directory fv/mac 

module mac(clk, rstb, IN, W, OUT, add_result, mult_result,
     debug_cycle_cnt);
  input clk, rstb;
  input [3:0] IN, W;
  output [11:0] OUT, add_result;
  output [7:0] mult_result;
  output [3:0] debug_cycle_cnt;
  wire clk, rstb;
  wire [3:0] IN, W;
  wire [11:0] OUT, add_result;
  wire [7:0] mult_result;
  wire [3:0] debug_cycle_cnt;
  wire [11:0] acc_reg;
  wire [3:0] w_reg;
  wire [3:0] in_reg;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, n_0, n_1, n_2, n_3, n_4, n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_69, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_85, n_86, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_99;
  wire n_100, n_101, n_103, n_104, n_106, n_107, n_108, n_109;
  wire n_111, n_112, n_113, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_128, n_129;
  wire n_130, n_133, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_146, n_147, n_148, n_149;
  wire n_151, n_152, n_153, n_155, n_157, n_159, valid;
  DFFR_X1 \acc_reg_reg[11] (.RN (rstb), .CK (clk), .D (n_159), .Q
       (acc_reg[11]), .QN (UNCONNECTED));
  DFFR_X1 \acc_reg_reg[10] (.RN (rstb), .CK (clk), .D (n_157), .Q
       (acc_reg[10]), .QN (UNCONNECTED0));
  AND2_X1 g3451__8780(.A1 (add_result[11]), .A2 (valid), .ZN (n_159));
  DFFR_X1 \acc_reg_reg[9] (.RN (rstb), .CK (clk), .D (n_155), .Q
       (acc_reg[9]), .QN (n_0));
  AND2_X1 g3454__4296(.A1 (add_result[10]), .A2 (valid), .ZN (n_157));
  AND2_X1 g3453__3772(.A1 (add_result[9]), .A2 (valid), .ZN (n_155));
  OAI21_X1 g3455__1474(.A (n_153), .B1 (n_149), .B2 (n_152), .ZN
       (add_result[11]));
  OAI21_X1 g3457__4547(.A (n_153), .B1 (n_148), .B2 (n_152), .ZN
       (add_result[10]));
  DFFR_X1 \acc_reg_reg[8] (.RN (rstb), .CK (clk), .D (n_151), .Q
       (acc_reg[8]), .QN (UNCONNECTED1));
  OAI21_X1 g3458__9682(.A (n_153), .B1 (n_147), .B2 (n_152), .ZN
       (add_result[9]));
  AND2_X1 g3459__2683(.A1 (add_result[8]), .A2 (valid), .ZN (n_151));
  XNOR2_X1 g3460__1309(.A (n_144), .B (n_116), .ZN (n_149));
  DFFR_X1 \acc_reg_reg[7] (.RN (rstb), .CK (clk), .D (n_146), .Q
       (acc_reg[7]), .QN (UNCONNECTED2));
  XNOR2_X1 g3463__6877(.A (n_143), .B (n_120), .ZN (n_148));
  XOR2_X1 g3464__2900(.A (n_140), .B (n_124), .Z (n_147));
  AND2_X1 g3465__2391(.A1 (add_result[7]), .A2 (valid), .ZN (n_146));
  OAI21_X1 g3461__7675(.A (n_153), .B1 (n_139), .B2 (n_152), .ZN
       (add_result[8]));
  OAI211_X1 g3466__7118(.A (n_141), .B (n_112), .C1 (n_142), .C2
       (n_111), .ZN (n_144));
  NAND2_X1 g3467__8757(.A1 (n_142), .A2 (n_141), .ZN (n_143));
  OAI21_X1 g3470__1786(.A (n_153), .B1 (n_136), .B2 (n_152), .ZN
       (add_result[7]));
  AOI21_X1 g3468__5953(.A (n_117), .B1 (n_138), .B2 (n_137), .ZN
       (n_140));
  XNOR2_X1 g3469__5703(.A (n_138), .B (n_118), .ZN (n_139));
  NAND3_X1 g3472__7114(.A1 (n_138), .A2 (n_137), .A3 (n_125), .ZN
       (n_142));
  DFFR_X1 \acc_reg_reg[6] (.RN (rstb), .CK (clk), .D (n_133), .Q
       (acc_reg[6]), .QN (UNCONNECTED3));
  INV_X1 g3473(.A (n_135), .ZN (n_136));
  FA_X1 g3474__5266(.A (mult_result[7]), .B (acc_reg[7]), .CI (n_129),
       .CO (n_138), .S (n_135));
  AND2_X1 g3475__2250(.A1 (add_result[6]), .A2 (valid), .ZN (n_133));
  MUX2_X1 g3476__6083(.A (n_130), .B (mult_result[6]), .S (n_152), .Z
       (add_result[6]));
  DFFR_X1 \acc_reg_reg[5] (.RN (rstb), .CK (clk), .D (n_128), .Q
       (acc_reg[5]), .QN (UNCONNECTED4));
  FA_X1 g3478__2703(.A (mult_result[6]), .B (acc_reg[6]), .CI (n_121),
       .CO (n_129), .S (n_130));
  AND2_X1 g3479__5795(.A1 (add_result[5]), .A2 (valid), .ZN (n_128));
  MUX2_X1 g3480__7344(.A (n_122), .B (mult_result[5]), .S (n_152), .Z
       (add_result[5]));
  INV_X1 g3485(.A (n_123), .ZN (n_125));
  HA_X1 g3486__1840(.A (n_119), .B (n_0), .CO (n_123), .S (n_124));
  DFFR_X1 \acc_reg_reg[4] (.RN (rstb), .CK (clk), .D (n_115), .Q
       (acc_reg[4]), .QN (UNCONNECTED5));
  FA_X1 g3482__5019(.A (mult_result[5]), .B (acc_reg[5]), .CI (n_107),
       .CO (n_121), .S (n_122));
  XNOR2_X1 g3490__1857(.A (n_119), .B (acc_reg[10]), .ZN (n_120));
  NOR2_X1 g3491__9906(.A1 (n_117), .A2 (n_113), .ZN (n_118));
  XNOR2_X1 g3492__8780(.A (n_119), .B (acc_reg[11]), .ZN (n_116));
  AND2_X1 g3483__4296(.A1 (add_result[4]), .A2 (valid), .ZN (n_115));
  INV_X1 g3496(.A (n_113), .ZN (n_137));
  NAND2_X1 g3494__3772(.A1 (mult_result[7]), .A2 (acc_reg[10]), .ZN
       (n_112));
  NOR2_X1 g3495__1474(.A1 (mult_result[7]), .A2 (acc_reg[10]), .ZN
       (n_111));
  AND2_X1 g3493__4547(.A1 (mult_result[7]), .A2 (acc_reg[8]), .ZN
       (n_117));
  OAI21_X1 g3497__9682(.A (mult_result[7]), .B1 (acc_reg[9]), .B2
       (acc_reg[8]), .ZN (n_141));
  NOR2_X1 g3499__2683(.A1 (mult_result[7]), .A2 (acc_reg[8]), .ZN
       (n_113));
  NAND2_X1 g3500__1309(.A1 (mult_result[7]), .A2 (n_152), .ZN (n_153));
  MUX2_X1 g3484__6877(.A (n_108), .B (mult_result[4]), .S (n_152), .Z
       (add_result[4]));
  INV_X1 g3501(.A (mult_result[7]), .ZN (n_119));
  AOI21_X1 g3502__2900(.A (n_85), .B1 (n_109), .B2 (n_92), .ZN
       (mult_result[7]));
  XNOR2_X1 g3503__2391(.A (n_109), .B (n_93), .ZN (mult_result[6]));
  DFFR_X1 \acc_reg_reg[3] (.RN (rstb), .CK (clk), .D (n_106), .Q
       (n_34), .QN (acc_reg[3]));
  FA_X1 g3488__7675(.A (mult_result[4]), .B (acc_reg[4]), .CI (n_100),
       .CO (n_107), .S (n_108));
  NOR2_X1 g3507__7118(.A1 (n_104), .A2 (n_90), .ZN (n_109));
  AND2_X1 g3489__8757(.A1 (add_result[3]), .A2 (valid), .ZN (n_106));
  XNOR2_X1 g3508__1786(.A (n_103), .B (n_91), .ZN (mult_result[5]));
  NOR2_X1 g3509__5953(.A1 (n_103), .A2 (n_89), .ZN (n_104));
  MUX2_X1 g3498__5703(.A (n_101), .B (mult_result[3]), .S (n_152), .Z
       (add_result[3]));
  FA_X1 g3511__7114(.A (n_82), .B (n_76), .CI (n_96), .CO (n_103), .S
       (mult_result[4]));
  DFFR_X1 \acc_reg_reg[2] (.RN (rstb), .CK (clk), .D (n_99), .Q
       (acc_reg[2]), .QN (UNCONNECTED6));
  FA_X1 g3504__5266(.A (mult_result[3]), .B (n_34), .CI (n_94), .CO
       (n_100), .S (n_101));
  AND2_X1 g3506__2250(.A1 (add_result[2]), .A2 (valid), .ZN (n_99));
  MUX2_X1 g3510__6083(.A (n_95), .B (mult_result[2]), .S (n_152), .Z
       (add_result[2]));
  FA_X1 g3513__2703(.A (n_77), .B (n_45), .CI (n_81), .CO (n_96), .S
       (mult_result[3]));
  DFFR_X1 \acc_reg_reg[1] (.RN (rstb), .CK (clk), .D (n_88), .Q (n_39),
       .QN (acc_reg[1]));
  FA_X1 g3512__5795(.A (mult_result[2]), .B (acc_reg[2]), .CI (n_78),
       .CO (n_94), .S (n_95));
  NAND2_X1 g3520__7344(.A1 (n_86), .A2 (n_92), .ZN (n_93));
  XOR2_X1 g3515__1840(.A (n_90), .B (n_89), .Z (n_91));
  AND2_X1 g3516__5019(.A1 (add_result[1]), .A2 (valid), .ZN (n_88));
  INV_X1 g3525(.A (n_85), .ZN (n_86));
  MUX2_X1 g3518__1857(.A (n_79), .B (mult_result[1]), .S (n_152), .Z
       (add_result[1]));
  NAND2_X1 g3523__9906(.A1 (n_83), .A2 (w_reg[3]), .ZN (n_92));
  NOR3_X1 g3527__8780(.A1 (n_83), .A2 (in_reg[3]), .A3 (w_reg[3]), .ZN
       (n_85));
  FA_X1 g3517__4296(.A (n_47), .B (n_14), .CI (n_65), .CO (n_89), .S
       (n_82));
  FA_X1 g3529__3772(.A (n_15), .B (n_7), .CI (n_63), .CO (n_83), .S
       (n_90));
  XNOR2_X1 g3521__1474(.A (n_73), .B (n_80), .ZN (mult_result[2]));
  NAND2_X1 g3524__4547(.A1 (n_74), .A2 (n_80), .ZN (n_81));
  DFFR_X1 \cycle_cnt_reg[3] (.RN (rstb), .CK (clk), .D (n_75), .Q
       (debug_cycle_cnt[3]), .QN (n_13));
  FA_X1 g3522__9682(.A (n_39), .B (mult_result[1]), .CI (n_28), .CO
       (n_78), .S (n_79));
  FA_X1 g3531__2683(.A (n_17), .B (n_10), .CI (n_48), .CO (n_76), .S
       (n_77));
  DFFR_X1 \acc_reg_reg[0] (.RN (rstb), .CK (clk), .D (n_71), .Q (n_32),
       .QN (acc_reg[0]));
  AND2_X1 g3526__1309(.A1 (n_69), .A2 (n_66), .ZN (n_75));
  INV_X1 g3528(.A (n_72), .ZN (n_74));
  HA_X1 g3530__6877(.A (n_46), .B (n_25), .CO (n_72), .S (n_73));
  DFFR_X1 \cycle_cnt_reg[2] (.RN (rstb), .CK (clk), .D (n_67), .Q
       (debug_cycle_cnt[2]), .QN (n_2));
  AND2_X1 g3543__2900(.A1 (add_result[0]), .A2 (valid), .ZN (n_71));
  DFFR_X1 \OUT_reg[1] (.RN (rstb), .CK (clk), .D (n_55), .Q (OUT[1]),
       .QN (UNCONNECTED7));
  DFFR_X1 \OUT_reg[2] (.RN (rstb), .CK (clk), .D (n_57), .Q (OUT[2]),
       .QN (UNCONNECTED8));
  DFFR_X1 \OUT_reg[11] (.RN (rstb), .CK (clk), .D (n_54), .Q (OUT[11]),
       .QN (UNCONNECTED9));
  DFFR_X1 \OUT_reg[5] (.RN (rstb), .CK (clk), .D (n_56), .Q (OUT[5]),
       .QN (UNCONNECTED10));
  DFFR_X1 \OUT_reg[6] (.RN (rstb), .CK (clk), .D (n_59), .Q (OUT[6]),
       .QN (UNCONNECTED11));
  DFFR_X1 \OUT_reg[0] (.RN (rstb), .CK (clk), .D (n_51), .Q (OUT[0]),
       .QN (UNCONNECTED12));
  XOR2_X1 g3533__2391(.A (debug_cycle_cnt[3]), .B (n_49), .Z (n_69));
  DFFR_X1 \OUT_reg[7] (.RN (rstb), .CK (clk), .D (n_60), .Q (OUT[7]),
       .QN (UNCONNECTED13));
  DFFR_X1 \OUT_reg[9] (.RN (rstb), .CK (clk), .D (n_52), .Q (OUT[9]),
       .QN (UNCONNECTED14));
  DFFR_X1 \OUT_reg[8] (.RN (rstb), .CK (clk), .D (n_53), .Q (OUT[8]),
       .QN (UNCONNECTED15));
  DFFR_X1 \OUT_reg[3] (.RN (rstb), .CK (clk), .D (n_62), .Q (OUT[3]),
       .QN (UNCONNECTED16));
  DFFR_X1 \OUT_reg[4] (.RN (rstb), .CK (clk), .D (n_58), .Q (OUT[4]),
       .QN (UNCONNECTED17));
  DFFR_X1 \OUT_reg[10] (.RN (rstb), .CK (clk), .D (n_61), .Q (OUT[10]),
       .QN (UNCONNECTED18));
  XNOR2_X1 g3568__7675(.A (n_33), .B (mult_result[0]), .ZN
       (add_result[0]));
  DFFR_X1 \cycle_cnt_reg[0] (.RN (rstb), .CK (clk), .D (n_43), .Q
       (debug_cycle_cnt[0]), .QN (n_3));
  AND2_X1 g3535__7118(.A1 (n_50), .A2 (n_66), .ZN (n_67));
  INV_X1 g3550(.A (n_64), .ZN (n_65));
  DFFR_X1 \cycle_cnt_reg[1] (.RN (rstb), .CK (clk), .D (n_44), .Q
       (debug_cycle_cnt[1]), .QN (n_1));
  HA_X1 g3553__8757(.A (n_22), .B (n_8), .CO (n_63), .S (n_64));
  AND2_X1 g3561__1786(.A1 (n_35), .A2 (valid), .ZN (n_62));
  AND2_X1 g3562__5953(.A1 (n_27), .A2 (valid), .ZN (n_61));
  AND2_X1 g3563__5703(.A1 (n_31), .A2 (valid), .ZN (n_60));
  AND2_X1 g3564__7114(.A1 (n_42), .A2 (valid), .ZN (n_59));
  AND2_X1 g3565__5266(.A1 (n_26), .A2 (valid), .ZN (n_58));
  AND2_X1 g3566__2250(.A1 (n_29), .A2 (valid), .ZN (n_57));
  AND2_X1 g3567__6083(.A1 (n_38), .A2 (valid), .ZN (n_56));
  AND2_X1 g3554__2703(.A1 (n_40), .A2 (valid), .ZN (n_55));
  AND2_X1 g3555__5795(.A1 (n_36), .A2 (valid), .ZN (n_54));
  AND2_X1 g3556__7344(.A1 (n_37), .A2 (valid), .ZN (n_53));
  AND2_X1 g3557__1840(.A1 (n_30), .A2 (valid), .ZN (n_52));
  AND2_X1 g3558__5019(.A1 (n_41), .A2 (valid), .ZN (n_51));
  HA_X1 g3536__1857(.A (n_19), .B (debug_cycle_cnt[2]), .CO (n_49), .S
       (n_50));
  HA_X1 g3552__9906(.A (n_12), .B (n_11), .CO (n_47), .S (n_48));
  HA_X1 g3551__8780(.A (n_9), .B (n_16), .CO (n_45), .S (n_46));
  AND2_X1 g3570__4296(.A1 (n_66), .A2 (n_20), .ZN (n_44));
  AND2_X1 g3571__3772(.A1 (n_66), .A2 (n_3), .ZN (n_43));
  AND2_X1 g3575__1474(.A1 (n_80), .A2 (n_24), .ZN (mult_result[1]));
  MUX2_X1 g3578__4547(.A (OUT[6]), .B (acc_reg[6]), .S (n_152), .Z
       (n_42));
  MUX2_X1 g3572__9682(.A (OUT[0]), .B (n_32), .S (n_152), .Z (n_41));
  MUX2_X1 g3573__2683(.A (OUT[1]), .B (n_39), .S (n_152), .Z (n_40));
  MUX2_X1 g3574__1309(.A (OUT[5]), .B (acc_reg[5]), .S (n_152), .Z
       (n_38));
  MUX2_X1 g3576__6877(.A (OUT[8]), .B (acc_reg[8]), .S (n_152), .Z
       (n_37));
  MUX2_X1 g3577__2900(.A (OUT[11]), .B (acc_reg[11]), .S (n_152), .Z
       (n_36));
  MUX2_X1 g3569__2391(.A (OUT[3]), .B (n_34), .S (n_152), .Z (n_35));
  NAND2_X1 g3585__7675(.A1 (n_21), .A2 (n_32), .ZN (n_33));
  MUX2_X1 g3580__7118(.A (OUT[7]), .B (acc_reg[7]), .S (n_152), .Z
       (n_31));
  MUX2_X1 g3581__8757(.A (OUT[9]), .B (acc_reg[9]), .S (n_152), .Z
       (n_30));
  MUX2_X1 g3583__1786(.A (OUT[2]), .B (acc_reg[2]), .S (n_152), .Z
       (n_29));
  NOR2_X1 g3588__5953(.A1 (acc_reg[0]), .A2 (n_23), .ZN (n_28));
  MUX2_X1 g3582__5703(.A (OUT[10]), .B (acc_reg[10]), .S (n_152), .Z
       (n_27));
  MUX2_X1 g3579__7114(.A (OUT[4]), .B (acc_reg[4]), .S (n_152), .Z
       (n_26));
  NOR2_X1 g3586__5266(.A1 (n_18), .A2 (n_6), .ZN (n_66));
  NAND2_X1 g3589__2250(.A1 (mult_result[0]), .A2 (n_25), .ZN (n_80));
  OAI22_X1 g3587__6083(.A1 (w_reg[0]), .A2 (in_reg[1]), .B1
       (in_reg[0]), .B2 (w_reg[1]), .ZN (n_24));
  INV_X1 g3590(.A (mult_result[0]), .ZN (n_23));
  NAND2_X1 g3591__2703(.A1 (n_5), .A2 (n_4), .ZN (n_22));
  INV_X1 g3598(.A (n_152), .ZN (n_21));
  HA_X1 g3584__5795(.A (debug_cycle_cnt[1]), .B (debug_cycle_cnt[0]),
       .CO (n_19), .S (n_20));
  NOR4_X1 g3599__7344(.A1 (debug_cycle_cnt[1]), .A2
       (debug_cycle_cnt[2]), .A3 (debug_cycle_cnt[0]), .A4 (n_13), .ZN
       (n_18));
  NOR2_X1 g3594__1840(.A1 (w_reg[2]), .A2 (in_reg[1]), .ZN (n_17));
  NOR2_X1 g3593__5019(.A1 (w_reg[2]), .A2 (in_reg[0]), .ZN (n_16));
  NOR2_X1 g3595__1857(.A1 (w_reg[2]), .A2 (in_reg[3]), .ZN (n_15));
  OR2_X1 g3596__9906(.A1 (in_reg[1]), .A2 (w_reg[3]), .ZN (n_14));
  NOR2_X1 g3597__8780(.A1 (w_reg[0]), .A2 (in_reg[0]), .ZN
       (mult_result[0]));
  AND4_X1 g3606__4296(.A1 (debug_cycle_cnt[0]), .A2 (n_1), .A3 (n_2),
       .A4 (n_13), .ZN (n_152));
  NOR2_X1 g3601__3772(.A1 (in_reg[2]), .A2 (w_reg[1]), .ZN (n_12));
  OR2_X1 g3602__1474(.A1 (w_reg[0]), .A2 (in_reg[3]), .ZN (n_11));
  OR2_X1 g3604__4547(.A1 (in_reg[0]), .A2 (w_reg[3]), .ZN (n_10));
  NOR2_X1 g3592__9682(.A1 (w_reg[0]), .A2 (in_reg[2]), .ZN (n_9));
  NOR2_X1 g3600__2683(.A1 (w_reg[1]), .A2 (in_reg[3]), .ZN (n_8));
  NOR2_X1 g3605__1309(.A1 (in_reg[2]), .A2 (w_reg[3]), .ZN (n_7));
  NOR2_X1 g3603__6877(.A1 (w_reg[1]), .A2 (in_reg[1]), .ZN (n_25));
  DFFR_X1 \w_reg_reg[0] (.RN (rstb), .CK (clk), .D (W[0]), .Q
       (UNCONNECTED19), .QN (w_reg[0]));
  DFFR_X1 \in_reg_reg[3] (.RN (rstb), .CK (clk), .D (IN[3]), .Q
       (UNCONNECTED20), .QN (in_reg[3]));
  DFFR_X1 \w_reg_reg[1] (.RN (rstb), .CK (clk), .D (W[1]), .Q
       (UNCONNECTED21), .QN (w_reg[1]));
  DFFR_X1 \w_reg_reg[3] (.RN (rstb), .CK (clk), .D (W[3]), .Q
       (UNCONNECTED22), .QN (w_reg[3]));
  DFFR_X1 \w_reg_reg[2] (.RN (rstb), .CK (clk), .D (W[2]), .Q (n_5),
       .QN (w_reg[2]));
  DFFR_X1 \in_reg_reg[2] (.RN (rstb), .CK (clk), .D (IN[2]), .Q (n_4),
       .QN (in_reg[2]));
  DFFR_X1 \in_reg_reg[0] (.RN (rstb), .CK (clk), .D (IN[0]), .Q
       (UNCONNECTED23), .QN (in_reg[0]));
  DFFR_X1 \in_reg_reg[1] (.RN (rstb), .CK (clk), .D (IN[1]), .Q
       (UNCONNECTED24), .QN (in_reg[1]));
  DFFR_X1 valid_reg(.RN (rstb), .CK (clk), .D (1'b1), .Q (valid), .QN
       (n_6));
endmodule

